name: Publish

on:
  push:
    paths:
      - src/**
      - www/**
      - .github/workflows/**

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: wasm-pack-action
        uses: jetli/wasm-pack-action@v0.4.0
      - name: Build WASM
        run: wasm-pack build --release --target web
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
      - run: npm ci
        working-directory: www
      - name: Build webpack project
        run: npm run build:prod --production
        working-directory: www
      - uses: easingthemes/ssh-deploy@4.0.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: "-rlDzv"
          SOURCE: "www/dist/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.REMOTE_TARGET }}
